Imports Microsoft.VisualBasic
'An abstract class for objects that auto-generate cookies every second.
Public MustInherit Class Generator
    Private MustOverride Static baseCost As Integer     'cost of the first one purchased
    Private MustOverride Static CpS As Double           'cookies per second generated by one of this object
    Private MustOverride Static quantity As Integer     'number of this type of generator created
    Private MustOverride Static totalProduced As Double 'number of cookies produced since beginning of game

    'Allows retrieval/editing of the CpS for a single generator of this type
    Public Static Property CpS() As Double
        Get
            Return CpS
        End Get
        Set(ByVal value As Double)
            Cps = value
        End Set
    End Property

    'Returns the base cost of the first object purchased
    Public Static Property getBaseCost() As Integer
        Get
            Return baseCost
        End Get
    End Property

    'Allows retrieval/editing of the quantity of this generator in existance
    Public Static Property quantity() As Integer
        Get
            Return quantity
        End Get
        Set(ByVal value As Integer)
            quantity += value
        End Set
    End Property

    'Allows for retrieval/editing of the total Cookies produced by this generator type
    Public Static Property totalProduced() As Double
        Get
            Return totalProduced
        End Get
        Set(ByVal value As Double)
            totalProduced += value
        End Set
    End Property
End Class
