'An abstract class for objects that auto-generate cookies every second.
Public MustInherit Class Generator
    Private baseCost As Integer     'cost of the first one purchased
    Private CpS As Double           'cookies per second generated by one of this object
    Private amount As Integer     'number of this type of generator created
    Private total As Double 'number of cookies produced since beginning of game
    Private currentCost As Long  'base cost * 1.15 (accurate for non-cursors?)

    'Allows retrieval/editing of the CpS for a single generator of this type
    Public MustOverride ReadOnly Property getCpS() As Double

    'Returns the base cost of the first object purchased
    Public MustOverride ReadOnly Property getBaseCost() As Integer

    'Allows retrieval/editing of the quantity of this generator in existance
    Public MustOverride Property Quantity() As Integer

    'Allows for retrieval/editing of the total Cookies produced by this generator type
    Public MustOverride Property TotalProduced() As Double

    'Retrieve the current cost for buying this generator
    Public MustOverride ReadOnly Property getCost() As Long

    'Called when this generator type has been purchased.  The next instance will cost 115% of the last
    Public MustOverride Sub updateCost()
End Class
