'An abstract class for objects that auto-generate cookies every second.
Public MustInherit Class Generator
    Private baseCost As Integer     'cost of the first one purchased
    Private CpS As Double           'cookies per second generated by one of this object
    Private amount As Integer     'number of this type of generator created
    Private total As Double 'number of cookies produced since beginning of game
    Private currentCost As Long  'base cost * 1.15 (accurate for non-cursors?)

    'Allows retrieval/editing of the CpS for a single generator of this type
    Public ReadOnly Property getCpS() As Double
        Get
            Return CpS
        End Get
    End Property


    'Returns the base cost of the first object purchased
    Public ReadOnly Property getBaseCost() As Integer
        Get
            Return baseCost
        End Get
    End Property


    'Allows retrieval/editing of the quantity of this generator in existance
    Public Property Quantity() As Integer
        Get
            Return amount
        End Get
        Set(ByVal value As Integer)
            amount += value
        End Set
    End Property

    'Allows for retrieval/editing of the total Cookies produced by this generator type
    Public Property TotalProduced() As Double
        Get
            Return total
        End Get
        Set(ByVal value As Double)
            total += value
        End Set
    End Property

    Public ReadOnly Property getCost() As Integer
        Get
            Return currentCost
        End Get
    End Property

    Public Sub updateCost()
        currentCost *= 1.15
    End Sub
End Class
